# Copyright (c) Alibaba, Inc. and its affiliates.
"""End-to-end demonstration of LLM co-evolution.

Verifies the complete loop:
    Agent describes a need
    → LLM (fake) generates plugin code
    → PluginValidator validates through multi-stage pipeline
    → self_management.plugin_install writes + registers the plugin
    → new plugin's tool is invocable through the registry

This is the ultimate self-evolution capability demonstration.
"""


import pytest


ECHO_PLUGIN_CODE = '''
"""Auto-generated echo plugin for E2E co-evolution test."""

from typing import Any
from leapflow.plugins.protocol import ToolMetadata


class EchoE2EPlugin:
    """Simple echo plugin generated by fake LLM."""
    
    @property
    def plugin_id(self) -> str:
        return "echo_e2e"
    
    @property
    def category(self) -> str:
        return "custom"
    
    @property
    def dependencies(self) -> list:
        return []
    
    def bind_runtime(self, **deps: Any) -> None:
        pass
    
    @property
    def tools(self) -> list:
        return [ToolMetadata(
            name="echo_e2e_test",
            description="Auto-generated echo tool for E2E test",
            parameters_schema={
                "type": "object",
                "properties": {
                    "message": {"type": "string"},
                },
                "required": ["message"],
            },
            handler=self._echo_handler,
            x_leapflow={"category": "custom", "risk_level": "read_only"},
        )]
    
    async def _echo_handler(self, message: str = "", **kwargs: Any) -> dict:
        return {"ok": True, "echoed": message, "source": "generated_plugin"}


plugin = EchoE2EPlugin()
'''


class _FakeLLM:
    """A canned LLM that returns the echo plugin code."""
    async def achat(self, messages):
        # Return the echo plugin code wrapped in a markdown fence to test extraction
        return f"```python\n{ECHO_PLUGIN_CODE}\n```"


@pytest.fixture
def cleanup_installed_plugin(tmp_path):
    """Provide a profile-scoped install dir and clean up registry/module state.

    Installs now write into a profile-scoped plugins directory (injected via
    bind_runtime), not the Python package dir, so the fixture yields that dir
    and tears down the registry fiber and sys.modules entry afterwards.
    """
    import sys

    plugin_id = "echo_e2e"
    install_dir = tmp_path / "plugins"
    install_dir.mkdir(parents=True, exist_ok=True)
    yield install_dir
    # Cleanup dynamically-loaded module + registry state
    sys.modules.pop(plugin_id, None)
    try:
        from leapflow.plugins import get_registry, get_scoped_registry
        reg = get_registry()
        scoped = get_scoped_registry()
        if plugin_id in reg.plugins:
            reg.unregister_plugin(plugin_id)
        if plugin_id in scoped._fibers:
            fiber = scoped._fibers.pop(plugin_id)
            try:
                fiber.dispose()
            except Exception:
                pass
    except Exception:
        pass


@pytest.mark.asyncio
async def test_llm_coevolution_end_to_end(cleanup_installed_plugin):
    """Complete co-evolution loop: generate → validate → install → invoke."""
    from leapflow.learning.plugin_generator import PluginGenerator, PluginGenerationRequest
    from leapflow.plugins import get_registry
    
    # === Step 1: Generate + validate ===
    generator = PluginGenerator(llm_provider=_FakeLLM())
    request = PluginGenerationRequest(
        plugin_id="echo_e2e",
        description="A simple tool that echoes its input message.",
    )
    gen_result = await generator.generate_and_validate(request)
    assert gen_result["ok"], f"Generation failed: {gen_result.get('error')}"
    assert "echo_e2e_test" in gen_result["exposed_tools"], f"Expected tool not exposed: {gen_result}"
    assert gen_result["requires_approval"] is True
    
    generated_code = gen_result["code"]
    print(f"[step 1] Generated + validated {len(generated_code)} chars of code")
    print(f"[step 1] Exposed tools: {gen_result['exposed_tools']}")
    
    # === Step 2: Install via self_management (approval-gated) ===
    reg = get_registry()
    reg.assemble()
    self_mgmt = reg.get_plugin("self_management")
    
    # Wire an approving gate
    class _ApprovedResult:
        approved = True
        denial_message = ""
    class _ApprovingGate:
        async def evaluate(self, descriptor):
            return _ApprovedResult()
    self_mgmt._plugin_approval_gate = _ApprovingGate()
    # Route installs into the profile-scoped tmp dir (not the package dir).
    self_mgmt.bind_runtime(plugin_install_dir=str(cleanup_installed_plugin))
    
    try:
        install_result = await self_mgmt._plugin_install_handler(
            plugin_id="echo_e2e",
            code=generated_code,
        )
        assert install_result["ok"], f"Install failed: {install_result.get('error')}"
        assert "echo_e2e_test" in install_result["installed_tools"]
        print(f"[step 2] Installed plugin: {install_result}")
        
        # Install wrote into the injected profile dir, NOT the package dir.
        assert (cleanup_installed_plugin / "echo_e2e.py").exists()
        import leapflow.plugins.tool_plugins as _plugins_pkg
        from pathlib import Path as _Path
        assert not (_Path(_plugins_pkg.__file__).parent / "echo_e2e.py").exists()
        
        # === Step 3: Verify plugin is registered and invocable ===
        assert "echo_e2e" in reg.plugins, "Plugin not in registry after install"
        assert "echo_e2e_test" in reg.tool_handlers, "Tool handler not registered"
        
        handler = reg.tool_handlers["echo_e2e_test"]
        result = await handler(message="hello from co-evolution")
        assert result["ok"] is True
        assert result["echoed"] == "hello from co-evolution"
        assert result["source"] == "generated_plugin"
        print(f"[step 3] Invoked tool: {result}")
        
    finally:
        self_mgmt._plugin_approval_gate = None
        self_mgmt._plugin_install_dir = None


@pytest.mark.asyncio
async def test_llm_coevolution_install_denied_without_approval(cleanup_installed_plugin):
    """Verify that plugin_install is blocked without approval."""
    from leapflow.learning.plugin_generator import PluginGenerator, PluginGenerationRequest
    from leapflow.plugins import get_registry
    
    generator = PluginGenerator(llm_provider=_FakeLLM())
    request = PluginGenerationRequest(plugin_id="echo_e2e", description="echo")
    gen_result = await generator.generate_and_validate(request)
    assert gen_result["ok"]
    
    reg = get_registry()
    reg.assemble()
    self_mgmt = reg.get_plugin("self_management")
    self_mgmt._plugin_approval_gate = None  # no gate → fail-closed
    
    install_result = await self_mgmt._plugin_install_handler(
        plugin_id="echo_e2e",
        code=gen_result["code"],
    )
    assert install_result["ok"] is False
    assert install_result.get("requires_approval") is True
    print(f"Install correctly blocked without gate: {install_result['error'][:80]}")
    
    # Verify NOT installed
    assert "echo_e2e" not in reg.plugins, "Plugin should NOT be installed without approval"


@pytest.mark.asyncio
async def test_llm_coevolution_invalid_code_rejected():
    """Verify that invalid LLM-generated code is rejected at validation stage."""
    from leapflow.learning.plugin_generator import PluginGenerator, PluginGenerationRequest
    
    class _BadLLM:
        async def achat(self, messages):
            return "import os\nos.system('rm -rf /')\nplugin = None"
    
    generator = PluginGenerator(llm_provider=_BadLLM())
    result = await generator.generate_and_validate(
        PluginGenerationRequest(plugin_id="malicious", description="bad")
    )
    assert result["ok"] is False
    assert "system" in result["error"] or "flagged" in result["error"].lower()
    print(f"Malicious code correctly rejected at stage '{result.get('stage')}'")
