# Copyright (c) Alibaba, Inc. and its affiliates.
"""MCP-to-Skill bridge — present MCP server tool collections as discoverable Skills.

Automatically wraps each connected MCP server's capability set into a generated
SKILL.md file so that the skill index, discovery tools, and LLM-facing skill
list can surface MCP-provided capabilities without manual authoring.

Design:
- Reads tool metadata from the live ``McpServerManager`` (or any object that
  satisfies the ``McpToolProvider`` Protocol defined here).
- Generates one SKILL.md per server under a ``_mcp_skills/`` subdirectory,
  clearly separated from builtin and user skills.
- Registration is optional: if no MCP integration is available the bridge is a
  silent no-op.
- All MCP imports are guarded so the module loads even when the ``mcp`` package
  is absent.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Protocol, Sequence, runtime_checkable

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Auto-generation marker (placed at the top of every generated SKILL.md)
# ---------------------------------------------------------------------------
_AUTO_GEN_HEADER = (
    "<!-- AUTO-GENERATED by McpSkillBridge — do not edit manually. -->\n"
    "<!-- Re-run bridge_all() to regenerate from live MCP server metadata. -->\n"
)

_MCP_SKILLS_SUBDIR = "_mcp_skills"


# ---------------------------------------------------------------------------
# Protocol abstraction — decouples the bridge from any concrete MCP client
# ---------------------------------------------------------------------------
@runtime_checkable
class McpToolProvider(Protocol):
    """Minimal contract for an object that can supply MCP tool metadata.

    Satisfied by ``McpManager`` in ``leapflow.platform.mcp_manager`` as well as
    any test double.  The bridge never calls tools — it only reads schemas.
    """

    def get_tool_schemas(self) -> List[Any]: ...


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class McpSkillEntry:
    """Compact record for a generated MCP skill."""

    server_name: str
    tool_count: int
    generated_path: str
    last_synced: str


@dataclass(frozen=True)
class _ToolInfo:
    """Internal helper for rendering tool documentation."""

    name: str
    original_name: str
    description: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    read_only: bool = False


# ---------------------------------------------------------------------------
# McpSkillBridge
# ---------------------------------------------------------------------------
class McpSkillBridge:
    """Bridge that generates SKILL.md files from connected MCP server tools.

    Usage::

        bridge = McpSkillBridge(mcp_manager, skills_dir=layout.skills_dir)
        entries = bridge.bridge_all()
        bridge.register_with_index(skill_index)

    If *provider* is ``None`` or does not satisfy ``McpToolProvider``, every
    public method degrades to a safe no-op.
    """

    def __init__(
        self,
        provider: Optional[McpToolProvider] = None,
        *,
        skills_dir: Optional[Path] = None,
    ) -> None:
        self._provider = provider if isinstance(provider, McpToolProvider) else None
        self._skills_dir = Path(skills_dir) if skills_dir else None
        self._entries: List[McpSkillEntry] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def discover_servers(self) -> Dict[str, List[_ToolInfo]]:
        """Return a mapping of *server_name* -> list of tool info.

        Groups the flat tool list from the provider by ``server_name``.
        Returns an empty dict when the provider is unavailable.
        """
        if self._provider is None:
            return {}

        try:
            schemas = self._provider.get_tool_schemas()
        except Exception as exc:
            logger.warning("mcp_bridge: failed to query tool schemas: %s", exc)
            return {}

        servers: Dict[str, List[_ToolInfo]] = {}
        for schema in schemas:
            info = self._schema_to_info(schema)
            if info is None:
                continue
            sname = getattr(schema, "server_name", "unknown")
            servers.setdefault(sname, []).append(info)
        return servers

    def generate_skill_md(self, server_name: str) -> Optional[str]:
        """Generate SKILL.md content for a single MCP server.

        Returns the Markdown string, or ``None`` if the server has no tools.
        """
        servers = self.discover_servers()
        tools = servers.get(server_name)
        if not tools:
            return None
        return self._render_skill_md(server_name, tools)

    def bridge_all(self) -> List[McpSkillEntry]:
        """Generate SKILL.md files for every connected MCP server.

        Writes files under ``<skills_dir>/_mcp_skills/<server_name>/SKILL.md``
        and returns a list of ``McpSkillEntry`` records.
        """
        if self._provider is None or self._skills_dir is None:
            return []

        servers = self.discover_servers()
        if not servers:
            return []

        mcp_dir = self._skills_dir / _MCP_SKILLS_SUBDIR
        mcp_dir.mkdir(parents=True, exist_ok=True)

        entries: List[McpSkillEntry] = []
        now_iso = datetime.now(timezone.utc).isoformat(timespec="seconds")

        for server_name, tools in servers.items():
            content = self._render_skill_md(server_name, tools)
            if content is None:
                continue
            skill_dir = mcp_dir / _sanitize_dir_name(server_name)
            skill_dir.mkdir(parents=True, exist_ok=True)
            skill_md = skill_dir / "SKILL.md"
            skill_md.write_text(content, encoding="utf-8")
            logger.info(
                "mcp_bridge: generated skill for server '%s' (%d tools) at %s",
                server_name, len(tools), skill_md,
            )
            entries.append(
                McpSkillEntry(
                    server_name=server_name,
                    tool_count=len(tools),
                    generated_path=str(skill_md),
                    last_synced=now_iso,
                )
            )

        self._entries = entries
        return entries

    def register_with_index(self, skill_index: Any) -> int:
        """Invalidate the skill index so generated MCP skills are picked up.

        The ``SkillIndex`` scans ``_mcp_skills/`` as sub-directories of
        ``skills_dir``, so we just need to bust the cache.  Returns the
        number of entries that were bridged.
        """
        if hasattr(skill_index, "invalidate"):
            skill_index.invalidate()
        return len(self._entries)

    @property
    def entries(self) -> List[McpSkillEntry]:
        """Previously bridged entries (populated after ``bridge_all()``)."""
        return list(self._entries)

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render_skill_md(
        self, server_name: str, tools: Sequence[_ToolInfo]
    ) -> Optional[str]:
        """Build the full SKILL.md text for one MCP server."""
        if not tools:
            return None

        tool_names = [t.name for t in tools]
        tags = _derive_tags(server_name, tools)
        triggers = _derive_triggers(server_name, tools)

        # ---- YAML frontmatter ----
        frontmatter_lines = [
            "---",
            f"name: mcp_{_sanitize_dir_name(server_name)}",
            f'description: "Auto-generated skill for MCP server: {server_name}"',
            "version: 0.0.0",
            "metadata:",
            "  leapflow:",
            '    category: "integration"',
            '    source: "mcp"',
            "    confidence: 0.8",
            "    quality_score: 0.9",
            "  hermes:",
            '    category: "integration"',
            f"    tags: {json.dumps(tags)}",
            f"    requires_tools: {json.dumps(tool_names)}",
            "platforms: []",
            "triggers:",
        ]
        for trig in triggers:
            frontmatter_lines.append(f'  - "{trig}"')
        frontmatter_lines.append("---")
        frontmatter = "\n".join(frontmatter_lines)

        # ---- Body ----
        body_parts: List[str] = [
            _AUTO_GEN_HEADER,
            f"# {server_name} (MCP Server)\n",
            "## Overview\n",
            (
                f"This skill provides access to the **{server_name}** MCP server, "
                f"which exposes {len(tools)} tool(s). The tools listed below are "
                "available for use once the MCP server connection is established.\n"
            ),
            "> **Note:** This skill requires an active MCP server connection. "
            "Ensure the server is configured and running before invoking these tools.\n",
            "## Available Tools\n",
        ]

        for tool in tools:
            body_parts.append(f"### `{tool.name}`\n")
            if tool.description:
                body_parts.append(f"{tool.description}\n")
            if tool.original_name != tool.name:
                body_parts.append(f"*Original name:* `{tool.original_name}`\n")
            ro_label = "read-only" if tool.read_only else "may have side effects"
            body_parts.append(f"*Effect:* {ro_label}\n")
            if tool.parameters and tool.parameters.get("properties"):
                body_parts.append("**Parameters:**\n")
                body_parts.append("| Name | Type | Required | Description |")
                body_parts.append("|------|------|----------|-------------|")
                props = tool.parameters.get("properties", {})
                required_set = set(tool.parameters.get("required", []))
                for pname, pschema in props.items():
                    ptype = pschema.get("type", "any")
                    pdesc = pschema.get("description", "")
                    req = "Yes" if pname in required_set else "No"
                    body_parts.append(f"| `{pname}` | {ptype} | {req} | {pdesc} |")
                body_parts.append("")

        # ---- Workflow template ----
        body_parts.append("## Workflow\n")
        body_parts.append(
            f"To accomplish tasks with the **{server_name}** server:\n"
        )
        body_parts.append(
            "1. Verify the MCP server connection is active.\n"
            "2. Identify the appropriate tool from the list above.\n"
            "3. Construct the required parameters based on the schema.\n"
            "4. Call the tool and interpret the result.\n"
            "5. For multi-step operations, chain tool calls in logical order.\n"
        )

        body_parts.append("## Error Handling\n")
        body_parts.append(
            "| Situation | Action |\n"
            "|---|---|\n"
            "| MCP server not connected | Report connection failure; suggest checking server config. |\n"
            "| Tool call times out | Retry once, then report timeout to user. |\n"
            "| Unknown tool name | List available tools and suggest closest match. |\n"
        )

        body = "\n".join(body_parts)
        return f"{frontmatter}\n\n{body}"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _schema_to_info(schema: Any) -> Optional[_ToolInfo]:
        """Convert a provider schema object to ``_ToolInfo``."""
        try:
            return _ToolInfo(
                name=getattr(schema, "name", ""),
                original_name=getattr(schema, "original_name", getattr(schema, "name", "")),
                description=getattr(schema, "description", ""),
                parameters=getattr(schema, "parameters", {}),
                read_only=getattr(schema, "read_only", False),
            )
        except Exception:
            return None


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

def _sanitize_dir_name(name: str) -> str:
    """Produce a filesystem-safe directory name from a server name."""
    return name.replace(" ", "_").replace("-", "_").replace(".", "_").lower()


def _derive_tags(server_name: str, tools: Sequence[_ToolInfo]) -> List[str]:
    """Derive a compact tag list from server name and tool descriptions."""
    tags: List[str] = ["mcp", server_name.lower().replace(" ", "-")]
    # Pick up to 3 unique keywords from tool descriptions
    seen: set[str] = set(tags)
    for tool in tools[:10]:
        for word in tool.description.split()[:5]:
            clean = word.strip(".,;:()").lower()
            if len(clean) > 3 and clean not in seen:
                tags.append(clean)
                seen.add(clean)
            if len(tags) >= 6:
                break
        if len(tags) >= 6:
            break
    return tags


def _derive_triggers(
    server_name: str, tools: Sequence[_ToolInfo]
) -> List[str]:
    """Derive trigger phrases for the generated skill."""
    triggers = [
        f"use {server_name}",
        f"{server_name} tools",
    ]
    # Add up to 3 triggers from tool names
    for tool in tools[:3]:
        if tool.original_name:
            triggers.append(tool.original_name.replace("_", " "))
    return triggers
