"""Default .env template for first-run auto-generation.

This content mirrors ``.env.example`` in the project root.  When the user runs
``leap`` for the first time and ``~/.leapflow/.env`` does not yet exist, this
template is written there so the user has a ready-to-edit configuration file.
"""

from __future__ import annotations

ENV_TEMPLATE = """\
# LeapFlow Configuration
# Auto-generated by LeapFlow on first run. Edit as needed.
#
# Only LEAPFLOW_LLM_API_KEY is required. All other values have sensible defaults.
# Uncommented lines show defaults; commented lines show optional overrides.

# ═══════════════════════════════════════════════════════════════════════
# LLM — OpenAI-compatible provider (DashScope, OpenAI, DeepSeek, etc.)
# ═══════════════════════════════════════════════════════════════════════
LEAPFLOW_LLM_API_KEY=
LEAPFLOW_LLM_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
LEAPFLOW_LLM_MODEL=qwen3.7-plus
LEAPFLOW_LLM_MAX_RETRIES=3

# ═══════════════════════════════════════════════════════════════════════
# Bridge / Host — communication between Python Brain and platform Host
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_BRIDGE_SOCKET defaults to /tmp/leapflow.sock (matches OS Host).
# Uncomment only if you need a non-standard socket location.
# LEAPFLOW_BRIDGE_SOCKET=/tmp/leapflow.sock
# Set to 1 to run Brain standalone with an in-process mock Host (no Swift).
LEAPFLOW_MOCK_HOST=0

# ═══════════════════════════════════════════════════════════════════════
# Storage — persistent state (memory, trajectories, skill library)
# ═══════════════════════════════════════════════════════════════════════
LEAPFLOW_DUCKDB_PATH=~/.leapflow/memory.duckdb

# ═══════════════════════════════════════════════════════════════════════
# Memory Providers — storage and retrieval configuration
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_MEMORY_WORKING_MAX_TOKENS=8192
# LEAPFLOW_MEMORY_EPISODIC_TTL_S=300.0
# LEAPFLOW_MEMORY_EPISODIC_MAX_ENTRIES=200
# LEAPFLOW_MEMORY_EVOLUTION_MAX_EPISODES=1000

# ═══════════════════════════════════════════════════════════════════════
# Logging & Audit
# ═══════════════════════════════════════════════════════════════════════
LEAPFLOW_LOG_LEVEL=INFO
LEAPFLOW_AUDIT_LOG_PATH=~/.leapflow/audit.jsonl

# ═══════════════════════════════════════════════════════════════════════
# Learning & Execution — SessionController behavior
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_LEARN_IDLE_TIMEOUT=300
# LEAPFLOW_LEARN_AUTO_DISTILL=true
# LEAPFLOW_CONFIRM_DEFAULT_LEVEL=confirm

# ═══════════════════════════════════════════════════════════════════════
# Imitation Learning Pipeline
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_PATTERN_LIBRARY_PATH=
# LEAPFLOW_SNAPSHOT_LEVEL_DEFAULT=light
# LEAPFLOW_INTENT_INFERENCE_ENABLED=true
# LEAPFLOW_INTENT_INFERENCE_LANGUAGE=zh

# ═══════════════════════════════════════════════════════════════════════
# Skill Code Generation
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_CODEGEN_SANDBOX=true
# LEAPFLOW_CODEGEN_MAX_RETRIES=2

# ═══════════════════════════════════════════════════════════════════════
# DAG Task Planner — GraphPlanner + TaskScheduler
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_MAX_DAG_CONCURRENCY=3
# LEAPFLOW_DAG_NODE_TIMEOUT=300

# ═══════════════════════════════════════════════════════════════════════
# Recording Mode — primary signal source selection
# ═══════════════════════════════════════════════════════════════════════
# Controls which signal channels are active during recording.
#   video        — continuous video recording + event timeline (recommended)
#   default      — full multimodal (structural events + screenshot perception)
#   vision_only  — only screenshot perception; no structural events
LEAPFLOW_RECORDING_MODE=video

# ═══════════════════════════════════════════════════════════════════════
# Video Recording (active when LEAPFLOW_RECORDING_MODE=video)
# ═══════════════════════════════════════════════════════════════════════
# Capture FPS for screen recording (lower = smaller files, 5 is sufficient).
# LEAPFLOW_VIDEO_FPS=5
# Resolution scale factor (0.0-1.0). Default 0.75 = 75% of native resolution.
# LEAPFLOW_VIDEO_RESOLUTION_SCALE=0.75
# Video codec: h264 (hardware-accelerated on macOS).
# LEAPFLOW_VIDEO_CODEC=h264
# Max seconds per video segment file before auto-splitting.
# LEAPFLOW_VIDEO_MAX_SEGMENT_S=600
# Directory for video segment cache.
# LEAPFLOW_VIDEO_CACHE_DIR=~/.leapflow/cache/video

# ── Video Analysis ──
# LEAPFLOW_VIDEO_VLM_URL_SCHEME=base64
# LEAPFLOW_VIDEO_L2_ENABLED=true
# LEAPFLOW_VIDEO_L3_ENABLED=true
# LEAPFLOW_VIDEO_MAX_L2_REQUESTS=10

# ── Video Segmentation ──
# LEAPFLOW_VIDEO_SEGMENTER_MIN_S=30
# LEAPFLOW_VIDEO_SEGMENTER_MAX_S=600
# LEAPFLOW_VIDEO_SEGMENTER_IDLE_GAP_S=15
# LEAPFLOW_VIDEO_SEGMENTER_APP_GAP_S=5

# ═════════════════════════════════════════════════════════════════════
# Learnability Assessment — filter recordings before distillation
# ═════════════════════════════════════════════════════════════════════
# LEAPFLOW_LEARNABILITY_ENABLED=true
# LEAPFLOW_LEARNABILITY_MIN_STEPS=3
# LEAPFLOW_LEARNABILITY_MIN_DURATION_S=5.0
# LEAPFLOW_LEARNABILITY_MAX_IDLE_RATIO=0.80
# LEAPFLOW_LEARNABILITY_MIN_ACTION_DIVERSITY=2
# LEAPFLOW_LEARNABILITY_LEARN_THRESHOLD=0.65
# LEAPFLOW_LEARNABILITY_ASK_THRESHOLD=0.40
# LEAPFLOW_LEARNABILITY_VLM_ENABLED=true
# LEAPFLOW_LEARNABILITY_LLM_ENABLED=true
# LEAPFLOW_LEARNABILITY_RULE_WEIGHT=0.4
# LEAPFLOW_LEARNABILITY_VLM_WEIGHT=0.3
# LEAPFLOW_LEARNABILITY_LLM_WEIGHT=0.3

# ═══════════════════════════════════════════════════════════════════════
# Visual Track — screenshot-based perception (default/vision_only modes)
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_VISUAL_TRACK_ENABLED=true
# LEAPFLOW_VISUAL_FRAME_CACHE_DIR=~/.leapflow/cache/frames
# LEAPFLOW_VLM_MODEL=
# LEAPFLOW_VLM_API_KEY=
# LEAPFLOW_VLM_BASE_URL=
# LEAPFLOW_PRIVACY_SENSITIVE_APPS=

# ═══════════════════════════════════════════════════════════════════════
# Perception Depth — keystroke/char capture and privacy controls
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_TEXT_CAPTURE_ENABLED=true
# LEAPFLOW_TEXT_CAPTURE_EXCLUDE_APPS=
# LEAPFLOW_TEXT_CAPTURE_SECURE_ROLES=AXSecureTextField
# LEAPFLOW_TEXT_CAPTURE_MAX_LENGTH=500
# LEAPFLOW_CLIPBOARD_MAX_LENGTH=1024

# ═══════════════════════════════════════════════════════════════════════
# Perceptual Field — fine-grained per-context perception control
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_PERCEPTUAL_FIELD_ENABLED=false
# LEAPFLOW_PERCEPTUAL_FIELD_CONFIG=~/.leapflow/perceptual_fields.yaml

# ═══════════════════════════════════════════════════════════════════════
# Context Learning Attention — signal/noise filtering during recording
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_ATTENTION_FOREGROUND_GATE=true
# LEAPFLOW_ATTENTION_GOAL_RELEVANCE_THRESHOLD=0.1
# LEAPFLOW_ATTENTION_NOISE_PATTERNS=
# LEAPFLOW_ATTENTION_WORKING_DIR_INFERENCE=true
# LEAPFLOW_ATTENTION_DOMAIN_WHITELIST=true
# LEAPFLOW_ATTENTION_CURIOSITY_EXPAND_THRESHOLD=0.7
# LEAPFLOW_ATTENTION_ACCURACY_CONTRACT_THRESHOLD=0.1

# ═══════════════════════════════════════════════════════════════════════
# Execution Loop — budget and recovery parameters
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_REACT_MAX_ITERATIONS=20
# LEAPFLOW_REACT_SOFT_LIMIT=14
# LEAPFLOW_REACT_WARNING_THRESHOLD=10
# LEAPFLOW_TOOL_MAX_ITERATIONS=30
# LEAPFLOW_COMPRESS_THRESHOLD=16
# LEAPFLOW_COMPRESS_KEEP_TAIL=4
# LEAPFLOW_MAX_TOOL_OUTPUT_CHARS=2000
# LEAPFLOW_ERROR_TRANSIENT_MAX_RETRIES=3
# LEAPFLOW_ERROR_RATE_LIMIT_BASE_DELAY=5.0

# ═════════════════════════════════════════════════════════════════════
# Interactive UX — streaming and progress display
# ═════════════════════════════════════════════════════════════════════
# LEAPFLOW_STREAM_OUTPUT=true
# LEAPFLOW_VERBOSE_PROGRESS=true

# ═══════════════════════════════════════════════════════════════════════
# Signal Fusion — event signals as VLM temporal anchors
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_SIGNAL_CHANNELS=all
# LEAPFLOW_SIGNAL_REACTIVE_CAPTURE=false
# LEAPFLOW_MHMS_FUSION_ENABLED=false

# ═══════════════════════════════════════════════════════════════════════
# Causal Inference — chain construction and heuristic scoring
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_CAUSAL_REORDER_WINDOW_MS=300
# LEAPFLOW_CAUSAL_BURST_LIMIT=50
# LEAPFLOW_CAUSAL_MAX_CHAIN_EVENTS=20
# LEAPFLOW_HEURISTIC_TIME_DECAY_S=0.5
# LEAPFLOW_HEURISTIC_SPACE_DECAY_PX=200.0
# LEAPFLOW_CAUSAL_WINDOW_S=3.0
# LEAPFLOW_CAUSAL_APP_WINDOW_OVERRIDES={}
# LEAPFLOW_CAUSAL_TIER3_ENABLED=false
# LEAPFLOW_CAUSAL_TIER3_CONFIDENCE_THRESHOLD=0.7

# ═══════════════════════════════════════════════════════════════════════
# Surprise Detection — event-level surprise annotation
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_SURPRISE_ENABLED=true
# LEAPFLOW_SURPRISE_STAT_WEIGHT=0.4
# LEAPFLOW_SURPRISE_TEMPORAL_WEIGHT=0.3
# LEAPFLOW_SURPRISE_PATTERN_WEIGHT=0.3
# LEAPFLOW_SURPRISE_ANNOTATION_THRESHOLD=0.5
# LEAPFLOW_SURPRISE_WARMUP_EVENTS=50

# ═══════════════════════════════════════════════════════════════════════
# World Model — Prediction Loop & Curiosity-Driven Learning
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_PREDICTION_ENABLED=true
# LEAPFLOW_PREDICTION_DELTA_THRESHOLD=0.3
# LEAPFLOW_CURIOSITY_ALPHA=0.4
# LEAPFLOW_CURIOSITY_BETA=0.3
# LEAPFLOW_CURIOSITY_GAMMA=0.3
# LEAPFLOW_CURIOSITY_AUTO_BALANCE=true
# LEAPFLOW_PREDICTION_BUDGET=50
# LEAPFLOW_COMPARISON_BUDGET=20
# LEAPFLOW_REPLAY_BUDGET=3
# LEAPFLOW_GRADING_BUDGET=5
# LEAPFLOW_DISTILLATION_BUDGET=2
# LEAPFLOW_REPLAY_ON_SESSION_END=true
# LEAPFLOW_PREDICTION_STRUCTURAL_BLEND=0.4
# LEAPFLOW_PREDICTION_SEMANTIC_BLEND=0.6
# LEAPFLOW_PREDICTION_SEMANTIC_THRESHOLD=0.1
# LEAPFLOW_PREDICTION_RAG_ADVANTAGE_FLOOR=-0.3
# LEAPFLOW_PREDICTION_FAILURE_ADVANTAGE=-0.5
# LEAPFLOW_REPLAY_REGRESSION_SAMPLE_SIZE=200
# LEAPFLOW_MEMORY_PRUNE_AGE_DAYS=90.0

# ═══════════════════════════════════════════════════════════════════════
# Semantic RAG & Budget Rebalancing
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_SEMANTIC_EMBEDDING_PROVIDER=tfidf
# LEAPFLOW_SEMANTIC_RERANK_WEIGHT=0.4
# LEAPFLOW_BUDGET_DISCOVERY_BASELINE=2
# LEAPFLOW_BUDGET_REGRESSION_BASELINE=1
# LEAPFLOW_AST_PRECHECK_ENABLED=true

# ═══════════════════════════════════════════════════════════════════════
# RPC Transport
# ═══════════════════════════════════════════════════════════════════════
# LEAPFLOW_RPC_TIMEOUT_DEFAULT=30.0
"""
